on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  importar-datos:
    runs-on: ubuntu-latest

    steps:
    - name: Clonar repositorio
      uses: actions/checkout@v3

    - name: Configurar R
      uses: r-lib/actions/setup-r@v2

    - name: Instalar paquetes R necesarios
      run: |
        Rscript -e 'install.packages(c("googlesheets4"))'

    - name: Crear archivo JSON con la clave de la cuenta de servicio
      run: |
        echo "${{ secrets.GSHEET4_ACCOUNT_KEY }}" > gs4_token.json
        cat gs4_token.json

    - name: Ejecutar script R
      run: Rscript 'TCO Demo Restaurante.Rmd'
