on:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  importar-datos:
    runs-on: ubuntu-latest

    steps:
      - name: Commit results
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git commit -m 'Data updated' || echo "No changes to commit"
          git push origin || echo "No changes to commit"
